export const WORLD_COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "New Zealand" },
  { code: "FR", name: "France" },
  { code: "DE", name: "Germany" },
  { code: "ES", name: "Spain" },
  { code: "IT", name: "Italy" },
  { code: "PT", name: "Portugal" },
  { code: "NL", name: "Netherlands" },
  { code: "BE", name: "Belgium" },
  { code: "CH", name: "Switzerland" },
  { code: "AT", name: "Austria" },
  { code: "DK", name: "Denmark" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "FI", name: "Finland" },
  { code: "IE", name: "Ireland" },
  { code: "PL", name: "Poland" },
  { code: "CZ", name: "Czech Republic" },
  { code: "HU", name: "Hungary" },
  { code: "RO", name: "Romania" },
  { code: "BG", name: "Bulgaria" },
  { code: "GR", name: "Greece" },
  { code: "HR", name: "Croatia" },
  { code: "SI", name: "Slovenia" },
  { code: "SK", name: "Slovakia" },
  { code: "LT", name: "Lithuania" },
  { code: "LV", name: "Latvia" },
  { code: "EE", name: "Estonia" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "CN", name: "China" },
  { code: "IN", name: "India" },
  { code: "SG", name: "Singapore" },
  { code: "HK", name: "Hong Kong" },
  { code: "MY", name: "Malaysia" },
  { code: "TH", name: "Thailand" },
  { code: "ID", name: "Indonesia" },
  { code: "PH", name: "Philippines" },
  { code: "VN", name: "Vietnam" },
  { code: "AE", name: "UAE" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "QA", name: "Qatar" },
  { code: "KW", name: "Kuwait" },
  { code: "BH", name: "Bahrain" },
  { code: "OM", name: "Oman" },
  { code: "IL", name: "Israel" },
  { code: "TR", name: "Turkey" },
  { code: "EG", name: "Egypt" },
  { code: "ZA", name: "South Africa" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "MA", name: "Morocco" },
  { code: "DZ", name: "Algeria" },
  { code: "TN", name: "Tunisia" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "AR", name: "Argentina" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "PE", name: "Peru" },
  { code: "VE", name: "Venezuela" },
  { code: "EC", name: "Ecuador" },
  { code: "UY", name: "Uruguay" },
  { code: "PY", name: "Paraguay" },
  { code: "BO", name: "Bolivia" },
  { code: "CR", name: "Costa Rica" },
  { code: "PA", name: "Panama" },
  { code: "GT", name: "Guatemala" },
  { code: "SV", name: "El Salvador" },
  { code: "HN", name: "Honduras" },
  { code: "NI", name: "Nicaragua" },
  { code: "DO", name: "Dominican Republic" },
  { code: "CU", name: "Cuba" },
  { code: "JM", name: "Jamaica" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "BS", name: "Bahamas" },
  { code: "BB", name: "Barbados" },
  { code: "IS", name: "Iceland" },
  { code: "LU", name: "Luxembourg" },
  { code: "MT", name: "Malta" },
  { code: "CY", name: "Cyprus" },
  { code: "RU", name: "Russia" },
  { code: "UA", name: "Ukraine" },
  { code: "BY", name: "Belarus" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "GE", name: "Georgia" },
  { code: "AM", name: "Armenia" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "MD", name: "Moldova" },
  { code: "RS", name: "Serbia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "ME", name: "Montenegro" },
  { code: "MK", name: "North Macedonia" },
  { code: "AL", name: "Albania" },
  { code: "XK", name: "Kosovo" },
].sort((a, b) => a.name.localeCompare(b.name));

export const LANGUAGE_MAPPINGS: Record<string, string[]> = {
  US: ['en-US'],
  GB: ['en-GB'],
  CA: ['en-CA', 'fr-CA'],
  AU: ['en-AU'],
  NZ: ['en-NZ'],
  FR: ['fr-FR'],
  DE: ['de-DE'],
  ES: ['es-ES'],
  IT: ['it-IT'],
  PT: ['pt-PT'],
  NL: ['nl-NL'],
  BE: ['nl-BE', 'fr-BE'],
  CH: ['de-CH', 'fr-CH', 'it-CH'],
  AT: ['de-AT'],
  DK: ['da-DK'],
  SE: ['sv-SE'],
  NO: ['no-NO'],
  FI: ['fi-FI'],
  IE: ['en-IE'],
  PL: ['pl-PL'],
  CZ: ['cs-CZ'],
  HU: ['hu-HU'],
  RO: ['ro-RO'],
  BG: ['bg-BG'],
  GR: ['el-GR'],
  HR: ['hr-HR'],
  SI: ['sl-SI'],
  SK: ['sk-SK'],
  LT: ['lt-LT'],
  LV: ['lv-LV'],
  EE: ['et-EE'],
  JP: ['ja-JP'],
  KR: ['ko-KR'],
  CN: ['zh-CN'],
  IN: ['hi-IN', 'en-IN'],
  SG: ['en-SG', 'zh-SG'],
  HK: ['zh-HK', 'en-HK'],
  MY: ['ms-MY', 'en-MY'],
  TH: ['th-TH'],
  ID: ['id-ID'],
  PH: ['en-PH', 'fil-PH'],
  VN: ['vi-VN'],
  AE: ['ar-AE', 'en-AE'],
  SA: ['ar-SA'],
  QA: ['ar-QA'],
  KW: ['ar-KW'],
  BH: ['ar-BH'],
  OM: ['ar-OM'],
  IL: ['he-IL', 'ar-IL'],
  TR: ['tr-TR'],
  EG: ['ar-EG'],
  ZA: ['en-ZA', 'af-ZA'],
  NG: ['en-NG'],
  KE: ['sw-KE', 'en-KE'],
  MA: ['ar-MA', 'fr-MA'],
  DZ: ['ar-DZ', 'fr-DZ'],
  TN: ['ar-TN', 'fr-TN'],
  BR: ['pt-BR'],
  MX: ['es-MX'],
  AR: ['es-AR'],
  CL: ['es-CL'],
  CO: ['es-CO'],
  PE: ['es-PE'],
  VE: ['es-VE'],
  EC: ['es-EC'],
  UY: ['es-UY'],
  PY: ['es-PY'],
  BO: ['es-BO'],
  CR: ['es-CR'],
  PA: ['es-PA'],
  GT: ['es-GT'],
  SV: ['es-SV'],
  HN: ['es-HN'],
  NI: ['es-NI'],
  DO: ['es-DO'],
  CU: ['es-CU'],
  JM: ['en-JM'],
  TT: ['en-TT'],
  BS: ['en-BS'],
  BB: ['en-BB'],
  IS: ['is-IS'],
  LU: ['lb-LU', 'de-LU', 'fr-LU'],
  MT: ['mt-MT', 'en-MT'],
  CY: ['el-CY', 'tr-CY'],
  RU: ['ru-RU'],
  UA: ['uk-UA'],
  BY: ['be-BY', 'ru-BY'],
  KZ: ['kk-KZ', 'ru-KZ'],
  UZ: ['uz-UZ'],
  GE: ['ka-GE'],
  AM: ['hy-AM'],
  AZ: ['az-AZ'],
  MD: ['ro-MD'],
  RS: ['sr-RS'],
  BA: ['bs-BA', 'hr-BA', 'sr-BA'],
  ME: ['sr-ME'],
  MK: ['mk-MK'],
  AL: ['sq-AL'],
  XK: ['sq-XK', 'sr-XK'],
};
